### PR TITLE
Introduce Windows to CI

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
Note that this pull request introduces Windows to the CI **BUT** does not fix the issues derived from it. It can either be used as an example or the issues can be fixed in the main branch, after which this can be rebased.

### CODE REVIEW

**Comment by elbrujohalcon** [comment]
Woah! I wasn't expecting `warning: LF will be replaced by CRLF in…` errors 😓 
@ElectronicRU do you think you will be able to fix them?

**Comment by ElectronicRU** [comment]
> Woah! I wasn't expecting `warning: LF will be replaced by CRLF in…` errors 😓
> @ElectronicRU do you think you will be able to fix them?

Yeah - `git -c core.autocrlf false` should do the trick.

**Comment by paulo-ferraz-oliveira** [comment]
If there's something you want me to do in the scope of this pull request let me know.

**Comment by ElectronicRU** [comment]
@paulo-ferraz-oliveira oh, no, grand work dude, didn't expect you'd find time to do it so quickly! Sorry for pinging your notifs!

**Comment by paulo-ferraz-oliveira** [comment]
Rebased over `main` and force-pushed to stimulate CI again.

**Comment by elbrujohalcon** [comment]
@paulo-ferraz-oliveira please check paulo-ferraz-oliveira/rebar3_format#1 🙏🏻

**Comment by paulo-ferraz-oliveira** [comment]
> @paulo-ferraz-oliveira please check [paulo-ferraz-oliveira#1](https://github.com/paulo-ferraz-oliveira/rebar3_format/pull/1) 🙏🏻

Let me check this on Monday. OTOH, I was under the impression you could change my pull request directly, as per "If checked, users with write access to AdRoll/rebar3_format can add new commits to your feature/windows_ci branch. You can always change this setting later." (option to the right)

**Comment by paulo-ferraz-oliveira** [comment]
I'm updating this so it uses the newly released `erlef/setup-beam@v1`, and maybe serves as a source for the other pending pull request, #268.

**Comment by paulo-ferraz-oliveira** [comment]
I'm closing this PR as it's not actually solving anything, it was just showing how to introduce Windows to CI.

**Pull request closed without merging**
