### PR TITLE
Inline simple funs even more aggressively

### LINKED ISSUE #142: Indent one-claused anonymous functions less severely
Currently, the default formatter indents…

```erlang
fun() -> something end,
```

…as…

```erlang
        fun () ->
                something
        end,
```

…which puts the function body actually 8-spaces into the `fun` moving code in high order functions like `lists:map/2` and others way too much to the right. The indentation is necessary for things like…

```erlang
        fun (one) ->
                the_one;
            (two) ->
                the_two
        end,
```

…but we could make one-clause anonymous functions a special case and indent them less heavily…

```erlang
        fun () ->
            something
        end,
```

### PR DESCRIPTION
**Pull request by elbrujohalcon**
When I fixed #142, I forgot to reduce…

```erlang
fun() ->
    x
end
```
…to…
```erlang
fun() -> x end
```

This PR solves that.

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
Would you be so kind as to have an option to disable this particular level of aggressiveness? 😛  

The only case I can remember when I do similar stuff is when I use references like `lists:foldl(fun doit/2, [], L)`.

**Comment by elbrujohalcon** [comment]
@paulo-ferraz-oliveira Ok. We'll add an option for this. We never thought we would find people who prefers [this](https://github.com/AdRoll/rebar3_format/pull/156/files#diff-75688b46ea428408253343e4091e1a92L695-L698)…
```erlang
Identity =
    fun(X) ->
        X
    end,
```
…over…
```erlang
Identity = fun(X) -> X end,
```
…but it seems we find you now :)

**Comment by elbrujohalcon** [comment]
@paulo-ferraz-oliveira option added. Let us know what you think.

**Comment by paulo-ferraz-oliveira** [comment]
Wait, when you mean
```erlang
fun() ->
    x
end
```
you mean the body containing exactly **only one instruction** (as in, e.g. with side effects).

Or does the "aggressiveness" you mention also mean turning
```erlang
fun() ->
    MyLongVariableName = [1, 2, 3, 4]
end
```
into
```erlang
fun() -> MyLongVariableName = [1, 2, 3, 4] end
```
, if it fits in a single line?

Because if it's "only one instruction" (with no assignment, for example), I can go either way. But if there's an assignment to a variable my reader-mind lost it.

**Unrelated** (let me know if we should start a new Issue): is `fun()` preferred over `fun ()`? Would it be tweakable?

**Comment by elbrujohalcon** [comment]
> Wait, when you mean
> 
> ```erlang
> fun() ->
>     x
> end
> ```
> 
> you mean the body containing exactly **only one instruction** (as in, e.g. with side effects).
> 
> Or does the "aggressiveness" you mention also mean turning
> 
> ```erlang
> fun() ->
>     MyLongVariableName = [1, 2, 3, 4]
> end
> ```
> 
> into
> 
> ```erlang
> fun() -> MyLongVariableName = [1, 2, 3, 4] end
> ```
☝️  The aggressiveness (that's now controlled by a parameter) will do this to your function. Check the funs in the test_app modules and you'll see all the examples there.

> Because if it's "only one instruction" (with no assignment, for example), I can go either way. But if there's an assignment to a variable my reader-mind lost it.
> 
Well… let's just say that if there is an assignment to a variable, that variable must be used later and if that's the case… then those two expressions will use a line each 😉 

> **Unrelated** (let me know if we should start a new Issue): is `fun()` preferred over `fun ()`? Would it be tweakable?
At the time of generating this issue, `fun()` is what the `default_formatter` will produce for funs with just one clause. Mostly because that's the typical style I found since I started working with Erlang. We might want to parameterize that behavior through an option… but I still don't know enough people preferring `fun () -> something end` over `fun() -> something end` to warrant such option.

@diegomanuel, @juanbono, @facundoolano : What do you say?

**Comment by paulo-ferraz-oliveira** [comment]
> Well… let's just say that if there is an assignment to a variable, that variable must be used later and if that's the case… then those two expressions will use a line each 😉

Unless you're doing 
```erlang
fun () -> _Unused = do_something() end
```
right?

Variable `_Unused` is assigned, strictly speaking (though probably intended as not).

And, if you use `dialyzer` it'll most surely complain that your function returns a "complex" value you're not using, which is why we keep adding
```erlang
_ = lager:...
```
all over the place.

**Comment by paulo-ferraz-oliveira** [comment]
> but I still don't know enough people preferring fun () -> something end over fun() -> something end

Fair enough. A small adaptation for me, I guess. I was used to writing JavaScript and Erlang at the same time, but much more used to JS' `function ()` _standard_ (as per JSLint), so this was "transported over".

FWIW, in OTP: `fun ()` has about 10% of the occurrences of `fun()`.

**Comment by paulo-ferraz-oliveira** [comment]
[Here's somebody](https://github.com/WhatsApp/erlfmt/issues/173#issuecomment-696551930) that preferred it as well. 😄

**Comment by elbrujohalcon** [comment]
> [Here's somebody](https://github.com/WhatsApp/erlfmt/issues/173#issuecomment-696551930) that preferred it as well. 😄

HA! That _somebody_ will likely never use this formatter anyway, right? It's not like I could convince him to switch by giving him an option to format funs as `fun () ->…`, can I? :trollface:

**Comment by juanbono** [comment]
> We might want to parameterize that behavior through an option… but I still don't know enough people preferring fun () -> something end over fun() -> something end to warrant such option.


I think both options are a good default and i think it is such a small change that even if i prefer `fun ()` (or `fun()`) i would not change the default formatter to have that

**Review by juanbono — APPROVED** [review]

**Pull request merged**
